# Generated by Django 3.0.5 on 2021-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('tittle', models.CharField(help_text='Car brand, year and complectation', max_length=100)),
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('lot_num', models.IntegerField(max_length=20)),
                ('auction', models.CharField(blank=True, choices=[('i', 'IAAI'), ('c', 'Copart')], default='i', max_length=1)),
                ('odometr', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('highlight', models.CharField(max_length=100)),
                ('primary_damage', models.CharField(max_length=100)),
                ('secondary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('fuel', models.CharField(blank=True, choices=[('g', 'Gas'), ('d', 'Diesel'), ('h', 'Hybrid'), ('e', 'Electrically')], default='g', max_length=1)),
                ('transmission', models.CharField(max_length=100)),
                ('drive', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('keys', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1)),
            ],
        ),
    ]
