# Generated by Django 3.0.5 on 2021-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lot_num',
            field=models.CharField(max_length=20),
        ),
    ]
